# 神奇九转策略配置

# 策略基本信息
strategy_name: "magic_nine"
description: "当市场连续上涨或下跌指定天数，产生逆向交易信号"

# 资金设置
initial_capital: 1000000  # 初始资金100万
commission: 0.0003        # 交易手续费率 0.03%
slippage: 0.0001          # 滑点率 0.01%

# 策略参数
period: 9                 # 连续天数，默认为9天

# 交易品种
symbols: ["AAPL", "MSFT", "GOOGL", "TSLA", "AMZN", "NVDA", "META", "QQQ", "SPY"]

# 风险控制
risk_control:
  max_position: 1.0       # 最大仓位比例，1.0表示满仓
  stop_loss: 0.02         # 止损比例，亏损2%止损
  take_profit: 0.05       # 止盈比例，盈利5%止盈
  max_drawdown: 0.1       # 最大回撤限制，回撤超过10%停止交易

# 测试参数
backtest:
  start_date: "2023-01-01"  # 回测开始日期
  end_date: "2023-12-31"    # 回测结束日期
  interval: "1m"            # 回测周期，1分钟K线 