# 参数优化配置

# 优化器参数
optimizer: "bayesian"      # 优化器类型: grid_search, genetic, bayesian
n_iterations: 100         # 迭代次数
n_initial_points: 10      # 初始样本点数量

# 遗传算法参数
population_size: 50       # 种群大小
generations: 20          # 进化代数
mutation_rate: 0.1       # 变异率
elite_size: 5           # 精英数量

# 贝叶斯优化参数
kernel: "matern"         # 核函数类型
nu: 2.5                 # Matern核函数参数

# 参数空间
param_space:
  period: [ 5, 10, 20 ]    # 周期参数
  threshold: [ 0.01, 0.02, 0.03, 0.04, 0.05 ]  # 阈值参数
  stop_loss: [ 0.02, 0.03, 0.04, 0.05 ]  # 止损参数
  take_profit: [ 0.04, 0.05, 0.06, 0.07, 0.08 ]  # 止盈参数

# 评估指标
metric: "sharpe_ratio"   # 评估指标: sharpe_ratio, sortino_ratio, calmar_ratio

# 输出参数
output_dir: "results/optimization"  # 输出目录
save_plots: true        # 保存图表 