# 实盘配置

# 交易参数
broker: "tiger"           # 经纪商
account: "default"        # 账户
initial_capital: 1000000  # 初始资金

# 策略参数
strategy: "magic_nine"    # 策略名称
version: "smart"          # 策略版本

# 风险参数
max_position: 1.0         # 最大仓位
max_drawdown: 0.20        # 最大回撤限制
stop_loss: 0.05           # 止损比例
take_profit: 0.10         # 止盈比例

# 监控参数
monitor_interval: 60      # 监控间隔(秒)
alert_threshold: 0.10     # 预警阈值

# 日志参数
log_level: "INFO"         # 日志级别
log_dir: "logs"           # 日志目录 